<?php
// Menangkap data yang dikirimkan dari form login
$username = $_POST['username'];
$password = $_POST['password'];

// Melakukan koneksi ke router Mikrotik menggunakan API PHP
require_once('RouterOS-API/pear/Net/RouterOS/Autoloader.php');
use \RouterOSAPI\RouterOSAPI;
$API = new RouterOSAPI();
$API->debug = false;
if ($API->connect('7.7.7.1', 'admin', '')) {

    // Membuat user hotspot dengan username dan password yang diterima dari form login
    $API->write('/ip/hotspot/user/add', false);
    $API->write('=name='.$username, false);
    $API->write('=password='.$password, false);
    $API->write('=profile=default', false);
    $API->write('=comment=Generated by Login Page', true);

    // Menampilkan pesan sukses dan memberikan tautan untuk kembali ke halaman login
    echo "<h1>User hotspot berhasil dibuat!</h1>";
    echo "<p>Username: ".$username."</p>";
    echo "<p>Password: ".$password."</p>";
    echo "<p>Silahkan <a href='index.html'>kembali ke halaman login</a>.</p>";
    
    $API->disconnect();

} else {
    // Menampilkan pesan kesalahan jika gagal terhubung ke router Mikrotik
    echo "Koneksi gagal!";
}
?>
